// this file defines a collection of neon color themes, each with primary, dark, light, and glow variations. These themes can be used throughout the application to maintain a consistent neon aesthetic. Each theme is structured as an object containing the color values and a CSS glow effect for easy application in styles.
import {
  CYAN, CYAN_DARK, CYAN_LIGHT,
  MAGENTA, MAGENTA_DARK, MAGENTA_LIGHT,
  PURPLE, PURPLE_DARK, PURPLE_LIGHT,
  RED, RED_DARK, RED_LIGHT,
  ACID_GREEN, ACID_GREEN_DARK, ACID_GREEN_LIGHT,
  ORANGE, ORANGE_DARK, ORANGE_LIGHT,
  YELLOW, YELLOW_DARK, YELLOW_LIGHT,
  TAN, TAN_DARK, TAN_LIGHT,
  MOON_GRAY, MOON_GRAY_DARK, MOON_GRAY_LIGHT,
  CRACKED_ICE, CRACKED_ICE_DARK, CRACKED_ICE_LIGHT,
  EVIL, EVIL_DARK, EVIL_LIGHT,
  LAVA, LAVA_DARK, LAVA_LIGHT, LAVA_YELLOW, LAVA_BLACK,
  METALLIC_SILVER, METALLIC_SILVER_LIGHT, METALLIC_GOLD, METALLIC_GOLD_LIGHT, METALLIC_BRONZE, METALLIC_BRONZE_LIGHT,
  ORGANIC_GREEN, ORGANIC_GREEN_LIGHT, ORGANIC_BROWN, ORGANIC_BROWN_LIGHT, ORGANIC_DARK_GREEN, ORGANIC_DARK_GREEN_LIGHT,
  WATER_DEEP_BLUE, WATER_DEEP_BLUE_LIGHT, WATER_AQUA, WATER_AQUA_LIGHT, WATER_LIGHT_BLUE, WATER_LIGHT_BLUE_LIGHT,
  CRYSTAL_LIGHT_BLUE, CRYSTAL_LIGHT_BLUE_LIGHT, CRYSTAL_PINK, CRYSTAL_PINK_LIGHT, CRYSTAL_WHITE, CRYSTAL_WHITE_LIGHT
} from "./colors";

export const NEON_THEMES = {
  cyan: {
    primary: CYAN,
    dark: CYAN_DARK,
    light: CYAN_LIGHT,
    glow: `0 0 16px ${CYAN}cc`,
  },
  magenta: {
    primary: MAGENTA,
    dark: MAGENTA_DARK,
    light: MAGENTA_LIGHT,
    glow: `0 0 16px ${MAGENTA}cc`,
  },
  purple: {
    primary: PURPLE,
    dark: PURPLE_DARK,
    light: PURPLE_LIGHT,
    glow: `0 0 16px ${PURPLE}cc`,
  },
  red: {
    primary: RED,
    dark: RED_DARK,
    light: RED_LIGHT,
    glow: `0 0 16px ${RED}cc`,
  },
  acidGreen: {
    primary: ACID_GREEN,
    dark: ACID_GREEN_DARK,
    light: ACID_GREEN_LIGHT,
    glow: `0 0 16px ${ACID_GREEN}cc`,
  },
  orange: {
    primary: ORANGE,
    dark: ORANGE_DARK,
    light: ORANGE_LIGHT,
    glow: `0 0 16px ${ORANGE}cc`,
  },
  yellow: {
    primary: YELLOW,
    dark: YELLOW_DARK,
    light: YELLOW_LIGHT,
    glow: `0 0 16px ${YELLOW}cc`,
  },
  earth: {
    primary: TAN,
    dark: TAN_DARK,
    light: TAN_LIGHT,
    glow: `0 0 16px ${TAN}cc`,
  },
  moon: {
    primary: MOON_GRAY,
    dark: MOON_GRAY_DARK,
    light: MOON_GRAY_LIGHT,
    glow: `0 0 16px ${MOON_GRAY}cc`,
  },
  ice: {
    primary: CRACKED_ICE,
    dark: CRACKED_ICE_DARK,
    light: CRACKED_ICE_LIGHT,
    glow: `0 0 16px ${CRACKED_ICE}cc`,
  },
  evil: {
    primary: EVIL,
    dark: EVIL_DARK,
    light: EVIL_LIGHT,
    glow: `0 0 16px ${EVIL}cc`,
  },
  lava: {
    primary: LAVA,
    dark: LAVA_DARK,
    light: LAVA_LIGHT,
    yellow: LAVA_YELLOW,
    black: LAVA_BLACK,
    glow: `0 0 16px ${LAVA}cc`,
  },
  metallicSilver: {
    primary: METALLIC_SILVER,
    dark: METALLIC_SILVER,
    light: METALLIC_SILVER_LIGHT,
    glow: `0 0 16px ${METALLIC_SILVER}cc`,
  },
  metallicGold: {
    primary: METALLIC_GOLD,
    dark: METALLIC_GOLD,
    light: METALLIC_GOLD_LIGHT,
    glow: `0 0 16px ${METALLIC_GOLD}cc`,
  },
  metallicBronze: {
    primary: METALLIC_BRONZE,
    dark: METALLIC_BRONZE,
    light: METALLIC_BRONZE_LIGHT,
    glow: `0 0 16px ${METALLIC_BRONZE}cc`,
  },
  organicGreen: {
    primary: ORGANIC_GREEN,
    dark: ORGANIC_GREEN,
    light: ORGANIC_GREEN_LIGHT,
    glow: `0 0 16px ${ORGANIC_GREEN}cc`,
  },
  organicBrown: {
    primary: ORGANIC_BROWN,
    dark: ORGANIC_BROWN,
    light: ORGANIC_BROWN_LIGHT,
    glow: `0 0 16px ${ORGANIC_BROWN}cc`,
  },
  organicDarkGreen: {
    primary: ORGANIC_DARK_GREEN,
    dark: ORGANIC_DARK_GREEN,
    light: ORGANIC_DARK_GREEN_LIGHT,
    glow: `0 0 16px ${ORGANIC_DARK_GREEN}cc`,
  },
  waterDeepBlue: {
    primary: WATER_DEEP_BLUE,
    dark: WATER_DEEP_BLUE,
    light: WATER_DEEP_BLUE_LIGHT,
    glow: `0 0 16px ${WATER_DEEP_BLUE}cc`,
  },
  waterAqua: {
    primary: WATER_AQUA,
    dark: WATER_AQUA,
    light: WATER_AQUA_LIGHT,
    glow: `0 0 16px ${WATER_AQUA}cc`,
  },
  waterLightBlue: {
    primary: WATER_LIGHT_BLUE,
    dark: WATER_LIGHT_BLUE,
    light: WATER_LIGHT_BLUE_LIGHT,
    glow: `0 0 16px ${WATER_LIGHT_BLUE}cc`,
  },
  crystalLightBlue: {
    primary: CRYSTAL_LIGHT_BLUE,
    dark: CRYSTAL_LIGHT_BLUE,
    light: CRYSTAL_LIGHT_BLUE_LIGHT,
    glow: `0 0 16px ${CRYSTAL_LIGHT_BLUE}cc`,
  },
  crystalPink: {
    primary: CRYSTAL_PINK,
    dark: CRYSTAL_PINK,
    light: CRYSTAL_PINK_LIGHT,
    glow: `0 0 16px ${CRYSTAL_PINK}cc`,
  },
  crystalWhite: {
    primary: CRYSTAL_WHITE,
    dark: CRYSTAL_WHITE,
    light: CRYSTAL_WHITE_LIGHT,
    glow: `0 0 16px ${CRYSTAL_WHITE}cc`,
  },
};
